services:

  db:
    container_name: postal-updates-database
    image: postgres:15
    environment:
      - POSTGRES_DB=updatesbase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5545:5432
    restart: unless-stopped