server:
  port: 8884
  forward-headers-strategy: framework   # exposes Swagger under Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka

spring:
  application:
    name: packing-list-service
  datasource:
    url: jdbc:postgresql://localhost:5544/packinglistbase
    username: user
    password: password
  jpa:
    show-sql: true

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    enabled: true
    filter: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'