server:
  port: 8885
  forward-headers-strategy: framework    # exposes Swagger under Gateway

spring:
  application:
    name: postal-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5556/postalbase
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  kafka:
    subscription-topic:
      name: subscription-topic
    updates-topic:
      name: updates-topic
    consumer:
      bootstrap-servers: localhost:29092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: postal-updates
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    enabled: true
    filter: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'