server:
  port: 8886

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    loadbalancer:
      enabled: true
      configurations: health-check
      health-check:
        interval: 10
        refetch-instances: true
        refetch-instances-interval: 20

    gateway:
      discovery:    # needed for gateway if Eureka is used
        locator:
          enabled: true
        #  lower-case-service-uri: true  # needed as Eureka capitalizes letters URI
          lower-case-service-id: true
      routes:
        - id: postal-service
          uri: lb://postal-service
          predicates:
            - Path=/postal-service/**
        - id: packing-list-service
          uri: lb://packing-list-service
          predicates:
            - Path=/packing-list-service/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8899/eureka