services:

  db:
    container_name: packinglist-database
    image: postgres:15
    environment:
      - POSTGRES_DB=packinglistbase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5544:5432
    restart: unless-stopped