server:
  port: 8886

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka

spring:
  application:
    name: composite-service
  cloud:
    openfeign:
      client:
        config:
          postal-client:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full