server:
  port: 8885
  forward-headers-strategy: framework    # exposes Swagger under Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka

spring:
  application:
    name: postal-service
  datasource:
    url: jdbc:h2:mem:postalbase
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console.enabled: true

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    enabled: true
    filter: true
